### ISSUE TITLE
Wrong comment on type inference in variables example

### ISSUE THREAD

**Issue by b-strauss** [johnpryan/dartbyexample#2]
``` dart
// 'var' declares a variable. Dart will infer the type.
var a = "initial";
```

Dart does not infer types. The type of `a` is `dynamic`.

**Comment by Pacane** [comment]
The analyzer will however infer what the type is and provide analysis during development.

**Comment by b-strauss** [comment]
Indeed, but inference would mean that this would not work in checked mode:

``` dart
var a = "foo";
b = true;
```

Since the type of `a` would be `String` and not `dynamic`.

**Comment by Pacane** [comment]
Yeah, yeah I agree, there's no "type inference" in the compilation/interpretation whatsoever. I was just pointing out that you can see autocompletion and the IDE knows information about the type being assigned with type `var` because of the analyzer.

**Comment by johnpryan** [comment]
"dartanalyzer will infer the type" seems like the correction we need to make here
