### ISSUE TITLE
Convention of naming unused variables/parameters/exceptions _

### ISSUE THREAD

**Issue by Pacane** [johnpryan/dartbyexample#4]
I feel like it'd be nice to mention the convention to have "unnamed" params/variables using "_" as the name.

Doing that will tell the analyzer to stop yelling about a parameter not being used (ie: in a catch exception block, if you're not using `e` you can just call it `_` and the analyzer won't warn you.)

Also, if you have multiple of these, you can still name them `_` and `__` in the case you have 2.

**Comment by johnpryan** [comment]
yep I agree this should get fixed and a section should for that feature

Thanks!
